[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dmr.py"
version = "0.0.1"
authors = [
  { name="Jasper", email="jasper@jazper.dk" },
]
description = "A small example package"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/j4asper/dmr.py"
"Bug Tracker" = "https://github.com/j4asper/dmr.py/issues"